apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-config
  namespace: ecommerce
data:
  EUREKA_SERVER_URL: "http://eureka-server:8761/eureka/"
  EUREKA_INSTANCE_HOSTNAME: "eureka-server"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
  namespace: ecommerce
data:
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "ecommerce"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: ecommerce
data:
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
